### ISSUE TITLE
Update runtime to 19.08

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.scoutshonour.Digital#12]

**Comment by MateusRodCosta** [comment]
Ah, I didn't know a new fdo runtime had been released. Also strangely I didn't get an email for this issue.

I will update my apps soonish. Probably still today.
Thanks for reminding me.

**Comment by MateusRodCosta** [comment]
It seems the 32-bits versions of the fdo runtimes aren't available yet. So this will take a while more.

**Comment by MateusRodCosta** [comment]
Sorry, I made a mistake when force-pushing, won't happen again.
