### ISSUE TITLE
Only the i386 version should be installable by the user

### ISSUE THREAD

**Issue by MateusRodCosta** [flathub/com.scoutshonour.Digital#2]
Currently if I use `flatpak remote-ls flathub` using the `--arch` parameter for all 4 architectures a flatpak currently can support,  the search will show this app for all of them. 
This game's flatpak is packaged in a way that it uses the python binary which is already distributed with the game, which is 32-bits and needs 32-bit libraries. So, `only-arches` is used to limit the distribution to only the i386 flatpak.

Using a x86_64 system and running `flatpak install flathub com.scoutshonour.Digital` installs the x86_64 version, which predictably fails to actually run. I have already checked the build pages after some commits and it seems to really don't do the build steps when it notices the architecture should be skipped.

Even so, for some reason this flatpak seems to be available for every architecture instead of just i386.
This could be fixed by undestanding why flathub makes it available for all arches and fixing that OR, since python is a interpreted language, just change the flatpak to use the python 2 interpreter from the runtime.

@TingPing Thoughts on this?

**Comment by TingPing** [comment]
It could be some accidental leftover of the builder i don't know. @alexlarsson or @ramcq would probably know more.

**Comment by Barthalion** [comment]
I wonder if test builds aren't cached and later uploaded anyway, even with `only-arches`.

**Comment by TingPing** [comment]
@alexlarsson @ramcq, Is there any way to solve this? The buildbot should probably delete old arches if a `flathub.json` specifies `only-arches` to avoid situations like this where broken unusable builds are left in the other arches.

**Comment by nedrichards** [comment]
@ramcq has manually purged the x86-64 version. This should be reflected in the repo when the next app is updated.

**Comment by ramcq** [comment]
(and arm and aarch64 - this is all due to https://github.com/flathub/buildbot-config/issues/1 - once you take an arch away by changing flatpak.json, it just lingers around like a bad smell...)

**Comment by MateusRodCosta** [comment]
I will do #9 instead. Closing.
